services:
  - type: web
    name: chess-pairings
    env: node
    plan: free
    buildCommand: |
      npm install
      apt-get update && apt-get install -y python3-pip python3-dev
      pip3 install requests beautifulsoup4 lxml html5lib
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
