services:
  - type: web
    name: chess-pairings
    env: node
    plan: free
    buildCommand: |
      npm install
      curl -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="/opt/render/.cargo/bin:$PATH"
      python3 -m pip install --upgrade pip
      python3 -m pip install --user -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: "/opt/render/project/src:/opt/render/.local/lib/python3.9/site-packages"
    autoDeploy: true
